const phone = '09125694789';
const data = {
  id: 'uuid',
  attributes: {
    services: {
      mci: {
        acl: [
          {
            name: 'CHILDAPN',
            access: 'WHITELIST',
          },
        ],
      },
    },
  },
};

// console.log(/^9[0-9]{9}$/.test(phone));

const persianDate = require('persian-date');
const getPersianDate = (date) => new persianDate(date).toLocale('en').format('YYYY-MM-DD');
const date = '1996-05-23';

const arr = {
  ringToneOrder: 0,
  ringToneDTO: {
    ringToneName: 'با تو',
    singerName: 'پویا بیاتی',
    licenseNumber: '91-7680',
    albumName: 'بگو سیب',
    producerName: 'تبیان',
    rbtId: 44059,
    priceDTOList: [
      {
        rbtDuration: 'ONE_MONTH',
        rbtDurationLocale: 'Monthly',
        price: 3000,
        discount: 0,
        priceAfterDiscount: 3000,
        hasDiscount: true,
      },
      {
        rbtDuration: 'ONE_DAY',
        rbtDurationLocale: 'Daily',
        price: 1000,
        discount: 0,
        priceAfterDiscount: 1000,
        hasDiscount: true,
      },
      {
        rbtDuration: 'ONE_WEEK',
        rbtDurationLocale: 'Weekly',
        price: 2000,
        discount: 0,
        priceAfterDiscount: 2000,
        hasDiscount: true,
      },
    ],
    ringToneGroup: {
      groupName: 'پاپ',
      externalId: '334ccea8-cea3-4d97-a710-57f83c5bab67',
      groupId: 30000,
    },
    externalId: 'C6EB70BE-BBFC-3FA4-E054-9C8E99223024',
    coverURI: 'http://static.sandbox.vas.mcci.local/dl/shared/cover/TE.P.Bayati.jpg',
    songURI: 'http://static.sandbox.vas.mcci.local/dl/shared/tones/44059.wav',
    instrumentalMusic: false,
  },
};


const fs= require('fs')
const txt=`RBTPurchaseUpdate,
RBTPurchaseByOTPCreate,
subscriberExpropriateRemoval,
subscriberExpropriateByOtpCreate,
subscriberAliveCheckCreate,
loyaltySubscriberRewardsInquiry,
saveSimServiceActivationCreate,
querybalance,
balanceOwnAccessInquiry,
SaveSimServiceActivationByOTPCreate,
refundInfoInquiry,
saveSimServiceInquiry,
subscriberAliveByAclInquiry,
pre2postPriceInquiry,
billSmsInquiry,
RBTInquiry,
activeServicesInquiry,
billSmsActivationCreate,
billSmsDeactivationRemove,
LRFMServicesInquiry,
refundCreate,
billEmailServiceInquiry,
billEmailServiceDeactivationRemove,
billByAclIdInquiry,
dtsPwaInquiry,
create,
pre2Post,
callMeBackCreate,
billInquiry,
installmentCreate,
pinPukInquiry,
mcaActivationCreate,
vasOtpRequestCreate,
simBlockByOTP,
vasActivationUpdate,
pre2PostByOtp,
voiceMailActivationCreate,
userOtpByAclIdCreate,
balanceInquiry,
usimActivationCreate,
vasDeactivationRemove,
simBlockInquiry,
mcaDeactivationRemove,
aclSwitchInformUpdate,
usimcheckMsisdnCreate,
cdrByAclInquiry,
mcaStatusInquiry,
usimByAclInquiry,
loyaltyScoreGiftCreate,
paidBillsHistoryInquiry,
blacklistInquiry,
roamingActivationCreate,
vasHistoryInquiry,
callMeBackInquiry,
blacklistsInquiry,
customPackageActivationByAclCreate,
packageActivationCreate,
loyaltyChanceJoinCreate,
loyaltyInvitation,
stopRenewalPackageUpdate,
loyaltyCharityJoinCreate,
imeiDevicesInquiry,
internetActivationCreate,
installmentInquiry,
childApnActivationCreate,
cdrByAclOtpInquiry,
loyaltyScoreInquiry,
loyaltyRegistration,
roamingDeactivationRemove,
childPackageInquiry,
usageSummaryInquiry,
allSimsBlockInquiry,
roamingStatusInquiry,
internetDeactivationRemove,
checkSimTypeOfMsisdnInquiry,
tariffServiceInquiry,
phoneTrackActivationCreate,
usimInquiryByCaptchaCreate,
childApnDeactivationRemove,
loyaltyChanceInquiry,
loyaltyCharityOwnAccessInquiry,
voiceMailDeactivationRemove,
subscriberInfoInquiry,
billPrintDeactivationRemove,
balanceDetailsInquiry,
checkGenderAgeByAclIdInquiry,
troubleTicketsInquiry,
customersLevelInquiry,
usimForAllAclsInquiry,
loyaltyReservedInquiry,
checkGenderAgeCustomerInquiry,
internetServiceInquiry,
voiceMailStatusInquiry,
billPrintStatusInquiry,
phoneTrackDeactivationRemove,
customPackageActivationCreate,
transferBalanceByMsisdnUpdate,
restrictionDeactivationRemove,
tollServiceDeactivationRemove,
suggestedPackageInquiry,
normalTariffServiceActivationCreate,
billDetailsByOtpInquiry,
billByCycleMsisdnInquiry,
activeVASServicesInquiry,
phoneTrackHistoryInquiry,
restrictionStatusInquiry,
advancePaymentBillInquiry,
removeSubscriberBlacklist,
transferBalanceByAclIdOtpUpdate,
studentInternetActivationCreate,
installmentPaymentsInquiry,
suggestedPackageActivationCreate,
subscriberInfoByOtpInquiry,
topupRechargeHistoryInquiry,
subscriberInfoByAclIdInquiry,
webchatConnectionLinkInquiry,
childApnStatusByMsisdnInquiry,
normalTariffServiceDeactivationRemove,
subscriberInfoOwnAccessInquiry,
checkSubscriberPrepaidsFreesimInquiry,
subscriberExpropriationBlockStateInquiry,
loyaltyPackageCategoriesByAclIdInquiry,
studentInternetDeactivationRemove,
loyaltyPointOnlyPackageActivationCreate,`

const arr1 = txt.split(',').map(val=>val.trim('\n'))

 arr1.sort((a,b)=>{
  if(a.length>b.length) return 1
  if(a.length<b.length) return -1
  if(a.length===b.length) return 0
 })

arr1.forEach(val=>{
  fs.appendFileSync('./test.txt',`${val} ,\n`)
})